### ISSUE TITLE
Clarify How To Import This Module

### ISSUE THREAD

**Issue by dayfine** [krisk/Fuse#209]
Though it might be obvious to many, it was a bit frustrating when my friend and I could not get "import Fuse from 'fuse'" to work.

The official way should be I guess "import Fuse from 'fuse.js'"

I know it might be obvious, but can we just put this in readme.md and also the description on the npm site? Thanks!

**Comment by micahcourey** [comment]
This should work:

import * as Fuse from 'fuse.js';

**Comment by zivchen** [comment]
> This should work:
> 
> import * as Fuse from 'fuse.js';
Doesnt work 
new Fuse(collection, options) => Error Fuse is not a constructor

**Comment by pepijnolivier** [comment]
None of the above worked for me, but this notation did:

```
import Fuse from 'fuse.js/dist/fuse.min.js';
```

**Comment by danbraik** [comment]
still a problem for me.
`const index = Fuse.createIndex<MyType>(
 keys: ['key1', 'key2']
 list: list
)`
is refused.

**Comment by ghorbanzade** [comment]
I also think there appears to be a problem here.
`import * as Fuse from 'fuse.js'` satisfies the type checker but throws TypeError at runtime in v5.1.0 when instantiating a Fuse object: `fuse_js__WEBPACK_IMPORTED_MODULE_0__ is not a constructor`.
Not an expert but I suspect this is happening because the Fuse constructor clashes with the Fuse namespace?
One ugly workaround in TypeScript 2.7 or later is to use default import by enabling `allowSyntheticDefaultImports` and `esModuleInterop` and switching to `import Fuse from 'fuse.js'`. But I wish you can provide some advice on the right fix? This was not an issue in v3.4.5.

**Comment by cojocaru-dragos-alexandru** [comment]
> I also think there appears to be a problem here.
> `import * as Fuse from 'fuse.js'` satisfies the type checker but throws TypeError at runtime in v5.1.0 when instantiating a Fuse object: `fuse_js__WEBPACK_IMPORTED_MODULE_0__ is not a constructor`.
> Not an expert but I suspect this is happening because the Fuse constructor clashes with the Fuse namespace?
> One ugly workaround in TypeScript 2.7 or later is to use default import by enabling `allowSyntheticDefaultImports` and `esModuleInterop` and switching to `import Fuse from 'fuse.js'`. But I wish you can provide some advice on the right fix? This was not an issue in v3.4.5.

Thanks, this did the trick for me when nothing else did.

**Comment by ghorbanzade** [comment]
Update: It seems what I reported earlier is also reported in #384 and investigated in: https://github.com/angular/angular-cli/issues/17393. If the proposed fix is reasonable to you, I volunteer to make the change.

**Comment by krisk** [comment]
Should be fixed as of fuse.js@5.2.1: https://github.com/krisk/Fuse/issues/384

**Comment by ghorbanzade** [comment]
Thank you @krisk for cutting a release so fast!

**Comment by therealsuji** [comment]
if anyone got  this error fuse_min_js_1.default is not a constructor import fuse like this
`var Fuse = require('fuse.js');`

**Comment by kikar** [comment]
@krisk I still have a problem with latest version (5.2.3):
`import Fuse from 'fuse.js';`

and here is my tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "incremental": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "suppressImplicitAnyIndexErrors": true,
    "noImplicitAny": true,
    "skipLibCheck": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": false,
    "strictNullChecks": false,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "removeComments": true,
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*"]
    },
    "typeRoots": ["typings", "node_modules/@types"]
  },
}
```

I'm getting the following error: `TypeError: fuse_js_1.default is not a constructor`

**Comment by kbpontius** [comment]
Seeing this on 6.0.0 as well, unfortunately.

**Comment by kikar** [comment]
I don't see any changes from 5.2.3 in how the module is exported: https://github.com/krisk/fuse/compare/v5.2.3...v6.0.0
In fact is still not working

**Comment by kikar** [comment]
`import Fuse from 'fuse.js';` is not working in version 6.0.0 for me.
If it's working for you @kbpontius, can you share your `tsconfig.json` and how you import it?

**Comment by german1311** [comment]
For CommonJs

`const Fuse = require('fuse.js/dist/fuse.common')`

diferences: https://fusejs.io/getting-started/different-builds.html

**Comment by niwla23** [comment]
Still not working for me, no matter what import statement

**Comment by Huwiinn** [comment]
2023 -ing

NOT WORKING THIS library

`const result = **fuse**.search(searchWord);`

'fuse' missing. where I go find this?

**Comment by naveedibcos** [comment]
not working for me either.

I am following this [sync fusion sample](https://stackblitz.com/edit/react-rpmfhr?file=index.js,index.html) and it is just not working for me with same runtime error. 'Fuse is not a constructor'

After I resolved the above error. I got the following error, which may again be an issue in fuse.js

`fuse.min.js:9 Uncaught TypeError: this.docs.forEach is not a function
    at e.value (fuse.min.js:9:1)
    at F (fuse.min.js:9:1)
    at e.value (fuse.min.js:9:1)
    at new e (fuse.min.js:9:1)
    at onFiltering (SearchBox.js:25:1)
    at Observer.notify (observer.js:101:1)
    at ComponentBase.trigger (component-base.js:259:1)
    at AutoComplete.searchLists (auto-complete.js:133:1)
    at DropDownList.onFilterUp (drop-down-list.js:1282:1)`

Can someone help with this ?

**Comment by shner-elmo** [comment]
7 years later and I'm not sure there is a solution :(

**Comment by sujeeet-kumar** [comment]
Doesn't work with nodev20 with type as `module`. Node looks for a local file and not a package.
